[package]
name = "vaillant_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.30"
ureq = { version="2.6.2", features = ["default", "cookies", "json"]}
