{
 "title": "Power and Yield",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "latestUsageTime",
    "query": "SELECT time*1000 FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds} ORDER BY time DESC LIMIT 1;"
   }
  ]
 },
 "panels": [
  { "title": "(Y+P)/P Ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest (Y+P)/P from ${latestUsageTime:date:DD.MM.YYYY}",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT time, ch_yp as '(Y+P)/P Heating', hw_yp as '(Y+P)/P Hot Water', total_yp as '(Y+P)/P Total' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, ch_yp as '(Y+P)/P Heating', hw_yp as '(Y+P)/P Hot Water', total_yp as '(Y+P)/P Total' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "(Y+P)/P",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT time, ch_yp as '(Y+P)/P Heating', hw_yp as '(Y+P)/P Hot Water', total_yp as '(Y+P)/P Total' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, ch_yp as '(Y+P)/P Heating', hw_yp as '(Y+P)/P Hot Water', total_yp as '(Y+P)/P Total' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Power/Yield Watt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT time, total_p as 'Power', total_y as 'Yield' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, total_p as 'Power', total_y as 'Yield' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Central Heating",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT time, ch_hp_p as 'Power Heat pump', ch_bo_p as 'Power Boiler', ch_hp_y as 'Yield Heat pump' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, ch_hp_p as 'Power Heat pump', ch_bo_p as 'Power Boiler', ch_hp_y as 'Yield Heat pump' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hot Water",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT time, hw_hp_p as 'Power Heat pump', hw_bo_p as 'Power Boiler', hw_hp_y as 'Yield Heat pump' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, hw_hp_p as 'Power Heat pump', hw_bo_p as 'Power Boiler', hw_hp_y as 'Yield Heat pump' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Y/P over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "(Y+P)/P and Outdoor Temperature",
   "type": "timeseries",
   "description": "Disregard latest/currernt Day",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "queryText": "SELECT time, total_yp as '(Y+P)/P Total' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, total_yp as '(Y+P)/P Total' FROM Usage WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT time, outdoor as 'Outdoor' FROM Temperature WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "rawQueryText": "SELECT time, outdoor as 'Outdoor' FROM Temperature WHERE time >= ${__from:date:seconds} AND time < ${__to:date:seconds};",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}